# -*- coding: utf-8 -*-
"""
/***************************************************************************
 E4Importer
                                 A QGIS plugin
 A plugin that allows to import E4 EDA data together with a GPX file to visualize the electrodermalactivity during a walk
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-03
        copyright            : (C) 2022 by Markus Löchtefeld
        email                : loechti@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load E4Importer class from file E4Importer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .e4_importer import E4Importer
    return E4Importer(iface)
